### ISSUE TITLE
Scope of project? (Collab?)

### ISSUE THREAD

**Issue by maedoc** [jcrist/symcc#4]
(Didn't see your email so thought an issue might do the trick..)

I came across your talk from the Python weekly and was impressed. I've started working on what may be a similar project both at a high level (SymPy expressions, [example generating OpenCL kernel for ODE integration](http://nbviewer.ipython.org/github/maedoc/maedoc.github.io/blob/master/OpenCL%20code%20generation%20for%20ODEs%20with%20SymPy.ipynb)) and low-level (AST visitors/transformers, quick demo [here](http://maedoc.github.io/tvb-sym-gen/workflows/cee.html), inspired by the micropass compiler framework paper). In the latter, there are some differences e.g. shape info is propagated explicitly where needed.

The reason at least for my projects is to have a compiler generating specialized neural network simulators for various configurations, and all that boils down to giant systems of difference equations. Perhaps this makes my goals more specific than yours?

I see a big potential for this approach, generating not only OpenCL & JS code, but also MATLAB (which is the tool of choice for most of my colleagues), so my question is to what extent our projects might overlap and we could agree to compare notes or code or whatever?

**Comment by moorepants** [comment]
Andy Terrel, one of the original authors of the sympy codegen stuff started this project too:

https://github.com/IgnitionProject/ignition

I spoke to him about it some, and he was designing it to be a new generation of what he'd done before. Last time I saw him he said he'd abandoned it though. Just thought I'd put that on people's radar.

**Comment by jcrist** [comment]
@maedoc: your project looks super interesting, and is definitely another approach. This is mainly an experimental fork of the codegen stuff for SymPy, where I'm trying out some new framework ideas. Currently sympy "supports" indexed loops like you'd need for solving difference equations, but the framework behind it is inflexible and bug-ridden. 

What I'm building here is a ground-up redo that should allow other specific projects to use this functionality and wrap it in some nicer (but application specific) api calls. You're more than welcome to help, although currently I'm just playing around with some thoughts and laying out the design of the remaining components.

@moorepants: Thanks, I hadn't seen that before. Looks interesting, although I'm not a fan of the interface.
